### ISSUE TITLE
Help needed - using @fixture to parametrize a test

### ISSUE THREAD

**Issue by DavidDahan1** [smarie/python-pytest-cases#235] opened 2021-11-07 21:35 UTC
Hey fellow maintainers, I'll be glad to have your guidance.. 

I'm trying to use pytest cases to parameterize a test with a list of tuples(str, iterable) that is yielded from a (pytest-cases)@fixture, but something isn't working for me. 

It goes like the following:

```python
# We have a native @pytest.fixture that yield a value
@pytest.fixture
def give_some_val():
    return val

# Then I use this val in a pytest-cases @fixture so I can use it to parameterized my test later
@fixture
def prepare_params(give_some_val):
    val_to_list_of_tuples = data_manipulation(give_some_val)
    yield val_to_list_of_tuples
```

To clarify, the yielded value looks something like:
[('event_name': {'uuid1','uuid2'}), ('another_event_name': {'uuid3', 'uuid4'}),(..),....] 
again, list of tuples(string, set) .

when I try to implement this (either with @paytest.mark.parametrize or via @parametrize) like so:

```python
@parametrize(argsnames="event,data", argvals="prepare_params"
def test(event, data, another_native_pytest_fixture):
      assert make_sense(data, another_native_pytest_fixture), f"{event} failed"`
```

it seems like pytest can't create more tests nodes.. 
instead, it creates just one test node and it fails to recognize the structure of ("name1,name2", list_of_tuples_with_2_elements)
instead it treats every element *in the list* as a single param. 
I mean:
event = ('event_name': {'uuid1','uuid2'})
data =  ('another_event_name': {'uuid3', 'uuid4'})

and that's it. no more test nodes. 

I've gone through the docs multiple times but I can't find the answer. 
Highly appreciate your time if you got so far!

**Comment by smarie** [comment] 2021-11-08 13:31
Hi @DavidDahan1, thanks for this issue ! I updated it because it was not readable "as is" ..
I'll have a look

**Comment by smarie** [comment] 2021-11-08 13:38
It seems that you want a fixture to return a list of parameters. This is not possible with `pytest`, by design. See this post that explains it in details : https://stackoverflow.com/a/56865893/7262247

See also this answer: https://github.com/smarie/python-pytest-cases/issues/205#issuecomment-842136833

Note that pytest-cases is not repsonsible for this limitation, it is the way fixtures and parameters are defined in pytest.

So you'll need to create a copy of `give_some_val` that is not a fixture, and call it in the middle of the pytest module in order to define the list in the parametrize

```python
val_to_list_of_tuples = data_manipulation(give_some_val_not_fixture)

@parametrize(argsnames="event,data", argvals=val_to_list_of_tuples)
def test(event, data, another_native_pytest_fixture):
      assert make_sense(data, another_native_pytest_fixture), f"{event} failed"`
```

**Comment by smarie** [comment] 2021-12-15 13:35
Closing this now - please feel free to reopen if the above answer does not correspond to your actual question

**Closed by smarie** 2021-12-15 13:35 UTC
