### ISSUE TITLE
'pytest_plugins' in a non-top-level conftest is no longer supported

### ISSUE THREAD

**Issue by fabaff** [smarie/python-pytest-cases#204] opened 2021-05-04 10:30 UTC
Test can no longer be run, e .g., during the package build process for distributions:

```bash
============================= test session starts ==============================
platform linux -- Python 3.8.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1 -- /nix/store/q6gfck5czr67090pwm53xrdyhpg6bx67-python3-3.8.9/bin/python3.8
cachedir: .pytest_cache
rootdir: /build/pytest-cases-3.4.6, configfile: setup.cfg, testpaths: pytest_cases/tests/
plugins: cases-3.4.6, asyncio-0.14.0
collected 0 items / 1 error                                                    

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
Defining 'pytest_plugins' in a non-top-level conftest is no longer supported:
It affects the entire test suite instead of just below the conftest as expected.
  /build/pytest-cases-3.4.6/pytest_cases/tests/conftest.py
Please move it to a top level conftest file at the rootdir:
  /build/pytest-cases-3.4.6
For more information, visit:
  https://docs.pytest.org/en/stable/deprecations.html#pytest-plugins-in-non-top-level-conftest-files
=========================== short test summary info ============================
ERROR
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.16s ===============================
```

**Comment by smarie** [comment] 2021-05-04 14:45
Thanks @fabaff  for reporting this.

I'll have a look.

**Comment by smarie** [comment] 2021-05-07 09:49
@fabaff it seems that this issue can not be reproduced by the CI: https://github.com/smarie/python-pytest-cases/runs/2526121779?check_suite_focus=true#step:8:88

Maybe this is just due to the command you're running ?

`pytest pytest_cases/tests/` should work.

By the way this default test path is written in `setup.cfg` so running pytest in the root folder should do the job too.

Let me know if this works for you

**Comment by smarie** [comment] 2021-05-18 13:08
@fabaff I'll close this now as it does not seem reproducible. Feel free to reopen if you do not agree!

**Closed by smarie** 2021-05-18 13:08 UTC
Labels: needs_reproducible_example
