### ISSUE TITLE
unpack_to is incompatible with generators

### ISSUE THREAD

**Issue by edmondo1984** [smarie/python-pytest-cases#130] opened 2020-08-25 16:58 UTC
Take the following fixture:

```python
@pytest_cases.fixture_plus(scope="module", unpack_to_)
def my_fixture():
     with mock.patch('my_top_module.my_sub_module.module_b.module_a') as module_a_mock:
          with mock.patch('my_top_module.my_sub_module.module_b.module_c') as module_c_mock:
                  module_a_mock.my_func = MagicMock(return_value='Hello world')
                  yield module_a_mock, module_c_mock
```

Fails with the following error:

```
    @pytest_fixture(name=argname, scope=scope, autouse=False, hook=hook)
    @with_signature("%s(%s, request)" % (argname, source_f_name))
    def _param_fixture(request, **kwargs):
        # ignore the "not used" marks, like in @ignore_unused
        if not is_used_request(request):
            return NOT_USED
        # get the required fixture's value (the tuple to unpack)
        source_fixture_value = kwargs.pop(source_f_name)
        # unpack: get the item at the right position.
>       return source_fixture_value[_value_idx]
E       TypeError: 'generator' object is not subscriptable
```

Is there a work around for the purpose?

**Comment by smarie** [comment] 2020-08-26 09:27
Thanks @edmondo1984 ! it seems that your code example is not working :( I'll work from the stackoverflow code until you fix it: https://stackoverflow.com/a/56869515/7262247

**Comment by smarie** [comment] 2020-08-26 09:33
The following works:

```python
from pytest_cases import fixture

@fixture(scope="module", unpack_into="a,c")
def my_fixture():
    yield 1, 2

def test_my_thing_one(a, c):
    assert (a, c) == (1, 2)

def test_my_thing_two(a, c):
    assert (a, c) == (1, 2)

```

Since I am not very familiar with `mock`, can you please fix the above example so that I can reproduce your error ? Thanks !

**Comment by smarie** [comment] 2020-08-26 09:40
I managed to make your code work:

```python
from unittest import mock
from pytest_cases import fixture

@fixture(scope="module", unpack_into="a,c")
def my_fixture():
    with mock.patch('json.encoder') as module_a_mock:
        with mock.patch('json.decoder') as module_c_mock:
            module_a_mock.my_func = mock.MagicMock(return_value='Hello world')
            yield module_a_mock, module_c_mock

def test_my_thing_one(a, c):
    pass

def test_my_thing_two(a, c):
    pass
```

So I guess that you probably use an old version of `pytest-cases`. Can you try to update to the latest version ?

**Comment by smarie** [comment] 2020-09-22 12:59
Closing this issue as it seems to be related to an old version. @edmondo1984 feel free to reopen if this is not the case

**Closed by smarie** 2020-09-22 12:59 UTC
